### PR TITLE
hi, again :)

### PR DESCRIPTION
**Pull request by oivoodoo**
I wrote spec for my pull request. please review it again. Thanks!

my examples:

https://gist.github.com/1517525
https://gist.github.com/1517523

### CODE REVIEW

**Comment by paulyoder** [comment]
I'm ok with your first commit that triggers the change event.

I'm also excited about your second commit that adds support for nested attributes.

I think there needs to be more discussion on the API and syntax for the nested attributes though.

The commit introduces a breaking change by setting the default bindingAttrConfig values from `id` to `name` for all element types. Is this change necessary? If `name` is to be used, it's easy enough to pass it in through the options object `Backbone.ModelBinding.bind(this, {  all: 'name' })`

I would also like to discuss the syntax for the nested attributes. Instead of using `parentAttribte[childAttribute]` what do you think about using `parentAttribute.childAttribute`? I seems a little more natural and straight forward.

**Comment by oivoodoo** [comment]
agree with this line "Backbone.ModelBinding.bind(this, { all: 'name' })", I can revert default binding attribute config.

But I don't like idea to work with nested attributes using point like 'parentAttribute.childAttribute'. As example in Rails you will see forms with names like 'parentAttribute[childAttribute]' and you can use this forms without any changes for backbone model binding. 

Also I've removed '_text' for select input because it's useless.
Basic steps for backbone:
1. render view with model
2. make any changes with model
3. sync(create, update) model with server. 
attribute_name_text is unknown column for model on the server side because you are usually sending only "attribute_name: value" to the server.

**Comment by paulyoder** [comment]
Good point on using square brackets instead of periods for nested attributes. I agree we should use the square brackets.

I don't know the original use case for adding the `_text` attribute for select inputs, so it might not be a big deal to remove it. @derickbailey do you know the use case for it?

**Comment by mxriverlynn** [comment]
the very first app i wrote with ModelBinding had a screen with a drop list among other fields. after the user hit save, the model would be sent over to a list view on the same screen and display the information the user entered.

i added the `_text` bit because the values in the drop list options were GUIDs (for identity) but I wanted to display the text of the option they had selected... the _text field stores that when an option is selected.

... i don't really think this was the best way to built the functionality i wanted, at this point. i should have made the server do a lookup based on the GUID and then return the text value back with the model's JSON, instead of using this plugin to handle that functionality.

so... yeah... i'm good with removing that bit from the functionality. :)

**Comment by mxriverlynn** [comment]
on `id` vs `name` and `[]` vs `.` ...

these choices are largely based on a set of conventions used in other languages. in rails, the use of `[]` and `name` go hand in hand because that's what rails does. in .net or other languages, though, the use of `.` and `id` are more common.

when i first wrote this plugin, i had the idea of language-based configuration where we could provide different presets for different language conventions... something like this:

`Backbone.ModelBinding.configure(Backbone.ModelBinding.RailsConventions)`

where the `RailsConventions` object would contain all of the configuration needed to work with an out-of-the-box rails setup. people could create their own configuration objects, of course. they wouldn't be limited to what we provided.

... maybe this is just a dream. maybe it's something we could do. i should probably log this as a separate ticket, though. :)

**Comment by oivoodoo** [comment]
# Happy New Year!!!

I am not sure about _RailsConventions_ because it smells like hardcode for me. One question about dot notations. If I have more then one same nested attributes on the page. How should I set name attribute for the columns?

Example:
    form any_model_with_photos
        model[photos][]
        model[photos][]

>  i should have made the server do a lookup based on the GUID and then return the text value back with the model's JSON, instead of using this plugin to handle that functionality.

I think you can render this options into the model options and use it without loading from server. Of course it's depending on situations.

**Pull request closed without merging**
