### PR TITLE
Update to Support Zepto and updated specs

### PR DESCRIPTION
**Pull request by interlock**
Updated specs to be friendly to Zepto, view.$(selector) does not work in zepto. Had to update the lib a bit more to catch some failing cases for specs. There are a few failed specs, due to zepto limitations.

### CODE REVIEW

**Comment by interlock** [comment]
I just noticed a possible flaw in the changes I made to support Zepto. I may pull this request again, write some specs and update accordingly.

I want to make sure it selects the correct element when multiple elements of the same ID exist in the document.

**Comment by mxriverlynn** [comment]
curious to know why you would have multiple elements with the same ID. that breaks the semantics of ID and I wouldn't expect it to behave in a predictable fashion.

**Comment by interlock** [comment]
I agree and it's a moot point. As far as I can tell, all the cases this could happen, happen within the context of a parent element/view. Submitting specs for this would only encourage people to do it, so best to leave it as is?

**Comment by mxriverlynn** [comment]
There's a missing semi-colon on line 152 of the dataBindConvention.spec.js file:

`expect(this.el.css('display').toBe('none');`

should be

`expect(this.el.css('display')).toBe('none');`

When I fix this syntax error, 5 of the specs in the dataBindConvetion.spec file fail. Can you get those fixed? I'll get this pulled in when you do.

**Comment by interlock** [comment]
Presto Chango? Fixed the issues you mentioned. Conditionally run tests if Zepto isn't installed, so ZeptoSpec runner is all green and so is the regular spec runner. Updated readme.md to reflect support for zepto and mention how input with no type doesn't work. Let me know if there is anything else.

**Pull request closed without merging**
