### PR TITLE
Added vars to the binders

### PR DESCRIPTION
**Pull request by jcreamer898**
That should do it.

### CODE REVIEW

**Comment by paulyoder** [comment]
@jcreamer898 it looks like your text editor reformatted the spacing in the file (e.g. adding a space between a ')' and '{', etc)

This makes it difficult to figure out what code changes were actually made.

Can you submit a new pull request with only the code changes.

**Comment by jcreamer898** [comment]
Try now.

**Comment by paulyoder** [comment]
+1 from me.

I haven't setup the ruby jasmine runner on my machine yet, so I didn't confirm the unit tests pass, so that will still need to be checked

**Comment by paulyoder** [comment]
confirmed the tests pass

**Comment by paulyoder** [comment]
this change has been pushed to the dev branch and will be part of the next release

**Comment by jcreamer898** [comment]
Good deal!

**Pull request closed without merging**
