### PR TITLE
Config binding attr

### PR DESCRIPTION
**Pull request by nieve**
Right, this feels to me a lot better;
The idea is passing a json configuration object to Backbone.ModelBinding.call().
Would be happy to hear your thoughts on this...

### CODE REVIEW

**Comment by mxriverlynn** [comment]
i'm going through this now

nit-picky observation... check your tabs vs spaces, and indent levels.  2 spaces, no tabs. be sure everything lines up correctly. look at the "diff" on the pull request and you'll see a lot of stuff doesn't line up.

other than that, looking good so far. i

**Comment by mxriverlynn** [comment]
i've pulled this into the dev branch. there are some other things i'm going to do before the next release.

**Comment by nieve** [comment]
Cool!
I started to replace tabs with 2 spaces, in case you'd like to integrate the
code with the right indentation, but I suppose you're ahead of me..

Thoroughly enjoyed this, if you need any help on anything else, give me a
shout :)

**Comment by mxriverlynn** [comment]
FYI - i got into a huge refactoring mode yesterday, and re-worked a lot of the codebase. your configuration stuff got consolidated and moved into it's own Backbone.ModelBinding.Configuration class... helps keep all the classes smaller and more focused. take a look and let me know what you think.

**Comment by nieve** [comment]
Dude that looks so much better & cleaner- you rock! :)

**Pull request closed without merging**
